CREATE TABLESPACE etam_DATA LOGGING DATAFILE 'd:\oracle\product\10.2.0\oradata\oraares\etam_DATA.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
 
CREATE TEMPORARY TABLESPACE etam_TEMP TEMPFILE 'd:\oracle\product\10.2.0\oradata\oraares\etam_TEMP.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 50M;
 
CREATE TABLESPACE etam_INDEX LOGGING DATAFILE 'd:\oracle\product\10.2.0\oradata\oraares\etam_INDEX.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;

CREATE TABLESPACE slgam_DATA LOGGING DATAFILE 'd:\oracle\product\10.2.0\oradata\oraares\slgam_DATA.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
 
CREATE TEMPORARY TABLESPACE slgam_TEMP TEMPFILE 'd:\oracle\product\10.2.0\oradata\oraares\slgam_TEMP.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 50M;
 
CREATE TABLESPACE slgam_INDEX LOGGING DATAFILE 'd:\oracle\product\10.2.0\oradata\oraares\slgam_INDEX.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;


CREATE USER etam IDENTIFIED BY etam
DEFAULT TABLESPACE etam_DATA TEMPORARY TABLESPACE etam_TEMP
QUOTA UNLIMITED ON etam_DATA
QUOTA UNLIMITED ON etam_INDEX;


CREATE USER slgam IDENTIFIED BY slgam
DEFAULT TABLESPACE slgam_DATA TEMPORARY TABLESPACE slgam_TEMP
QUOTA UNLIMITED ON slgam_DATA
QUOTA UNLIMITED ON slgam_INDEX;

GRANT CONNECT TO slgam;
grant execute on transformacoes to slgam;
grant execute on geometria9i to slgam;

GRANT CONNECT TO etam;
grant execute on transformacoes to etam;
grant execute on geometria9i to etam


