select * from ceproft_pa.lov_municipio t

update ceproft_pa.lov_municipio t set t.codigo='110001' where t.texto='Alta Floresta d Oeste';	          
update ceproft_pa.lov_municipio t set t.codigo='110009' where t.texto='Espigão d Oeste';               	
update ceproft_pa.lov_municipio t set t.codigo='110013' where t.texto='Machadinho d Oeste';            	
update ceproft_pa.lov_municipio t set t.codigo='110014' where t.texto='Nova Brasilândia d Oeste';       	
update ceproft_pa.lov_municipio t set t.codigo='110029' where t.texto='Santa Luzia d Oeste';           	
update ceproft_pa.lov_municipio t set t.codigo='110034' where t.texto='Alvorada d Oeste';              	
update ceproft_pa.lov_municipio t set t.codigo='110037' where t.texto='Alto Alegre do Parecis';        	
update ceproft_pa.lov_municipio t set t.codigo='110110' where t.texto='Itapuã d Oeste'	;                 
update ceproft_pa.lov_municipio t set t.codigo='110148' where t.texto='São Felipe d Oeste';            	
update ceproft_pa.lov_municipio t set t.codigo='150555' where t.texto='Pau d Arco'	;                     
update ceproft_pa.lov_municipio t set t.codigo='170600' where t.texto='Couto de Magalhães';             	
update ceproft_pa.lov_municipio t set t.codigo='171630' where t.texto='Pau d Arco';                    	
update ceproft_pa.lov_municipio t set t.codigo='210235' where t.texto='Buritirama'	;                     
update ceproft_pa.lov_municipio t set t.codigo='210594' where t.texto='Lagoa dos Rodrigues';            	
update ceproft_pa.lov_municipio t set t.codigo='210740' where t.texto='Olho d Água das Cunhãs'	;         
update ceproft_pa.lov_municipio t set t.codigo='210850' where t.texto='Pindaré Mirim';                 	
update ceproft_pa.lov_municipio t set t.codigo='220117' where t.texto='Barra d Alcântara' ;            	
update ceproft_pa.lov_municipio t set t.codigo='220710' where t.texto='Olho d Água do Piauí';           	
update ceproft_pa.lov_municipio t set t.codigo='240620' where t.texto='Lagoa d Anta'	;                   
update ceproft_pa.lov_municipio t set t.codigo='240840' where t.texto='Olho-d Água do Borges';         	
update ceproft_pa.lov_municipio t set t.codigo='250330' where t.texto='Cachoeira dos µndios';          	
update ceproft_pa.lov_municipio t set t.codigo='250870' where t.texto='Mãe d Água';                     	
update ceproft_pa.lov_municipio t set t.codigo='251040' where t.texto='Olho d Água';                   	
update ceproft_pa.lov_municipio t set t.codigo='251315' where t.texto='Santa Cecília de Umbuzeiro';     	
update ceproft_pa.lov_municipio t set t.codigo='251396' where t.texto='São Domingos de Pombal';        	
update ceproft_pa.lov_municipio t set t.codigo='2605459' where t.texto='Fernando de Noronha (Distrito Estadual)';	
update ceproft_pa.lov_municipio t set t.codigo='260760' where t.texto='Itamaracá';                     	
update ceproft_pa.lov_municipio t set t.codigo='270570' where t.texto='Olho d Água das Flores';         	
update ceproft_pa.lov_municipio t set t.codigo='270580' where t.texto='Olho d Água do Casado';          	
update ceproft_pa.lov_municipio t set t.codigo='270590' where t.texto='Olho d Água Grande';             	
update ceproft_pa.lov_municipio t set t.codigo='270630' where t.texto='Palmeira dos µndios';            	        
update ceproft_pa.lov_municipio t set t.codigo='270900' where t.texto='Tanque d Arca';                 	
update ceproft_pa.lov_municipio t set t.codigo='280320' where t.texto='Itaporanga d Ajuda';             	
update ceproft_pa.lov_municipio t set t.codigo='290050' where t.texto='Livramento do Brumado';          	
update ceproft_pa.lov_municipio t set t.codigo='291005' where t.texto='Dias d Ávila';                  	
update ceproft_pa.lov_municipio t set t.codigo='312161' where t.texto='Desembargador Otoni';           	
update ceproft_pa.lov_municipio t set t.codigo='312165' where t.texto='Senador Mourão';                	
update ceproft_pa.lov_municipio t set t.codigo='312290' where t.texto='Dona Euzébia';                   	
update ceproft_pa.lov_municipio t set t.codigo='312760' where t.texto='Gouvêa';                        	
update ceproft_pa.lov_municipio t set t.codigo='313180' where t.texto='Itabirinha de Mantena';         	
update ceproft_pa.lov_municipio t set t.codigo='314545' where t.texto='Olhos-d Água';                  	
update ceproft_pa.lov_municipio t set t.codigo='314780' where t.texto='Passa Vinte';                   	
update ceproft_pa.lov_municipio t set t.codigo='315053' where t.texto='Pingo d Água';                  	
update ceproft_pa.lov_municipio t set t.codigo='315150' where t.texto='Piuí';                           	
update ceproft_pa.lov_municipio t set t.codigo='315380' where t.texto='Queluzita';                     	
update ceproft_pa.lov_municipio t set t.codigo='320225' where t.texto='Governador Lindeberg';           	
update ceproft_pa.lov_municipio t set t.codigo='330023' where t.texto='Armação de Búzios';             	
update ceproft_pa.lov_municipio t set t.codigo='330590' where t.texto='Trajano de Morais';             	
update ceproft_pa.lov_municipio t set t.codigo='350260' where t.texto='Aparecida d Oeste';              	
update ceproft_pa.lov_municipio t set t.codigo='350780' where t.texto='Brodósqui';                     	
update ceproft_pa.lov_municipio t set t.codigo='351520' where t.texto='Estrela d Oeste';                	
update ceproft_pa.lov_municipio t set t.codigo='351800' where t.texto='Guarani d Oeste';               	
update ceproft_pa.lov_municipio t set t.codigo='352090' where t.texto='Ipauçu';                        	
update ceproft_pa.lov_municipio t set t.codigo='353060' where t.texto='Moji das Cruzes';                	
update ceproft_pa.lov_municipio t set t.codigo='353080' where t.texto='Moji-Mirim'	;                     
update ceproft_pa.lov_municipio t set t.codigo='353520' where t.texto='Palmeira d Oeste';              	
update ceproft_pa.lov_municipio t set t.codigo='354580' where t.texto='Santa Bárbara d Oeste';          	
update ceproft_pa.lov_municipio t set t.codigo='354610' where t.texto='Santa Clara d Oeste';            	
update ceproft_pa.lov_municipio t set t.codigo='354740' where t.texto='Santa Rita d Oeste';            	
update ceproft_pa.lov_municipio t set t.codigo='354930' where t.texto='São João do Pau d Alho';        	
update ceproft_pa.lov_municipio t set t.codigo='410715' where t.texto='Diamante d Oeste';               	
update ceproft_pa.lov_municipio t set t.codigo='411120' where t.texto='Itapejara d Oeste';             	
update ceproft_pa.lov_municipio t set t.codigo='411900' where t.texto='Pérola d Oeste';                	
update ceproft_pa.lov_municipio t set t.codigo='412135' where t.texto='Rancho Alegre d Oeste';         	
update ceproft_pa.lov_municipio t set t.codigo='412520' where t.texto='São Jorge d Oeste';             	
update ceproft_pa.lov_municipio t set t.codigo='412555' where t.texto='São Manuel do Paraná';          	
update ceproft_pa.lov_municipio t set t.codigo='420670' where t.texto='Herval d Oeste';                	
update ceproft_pa.lov_municipio t set t.codigo='421280' where t.texto='Piçarras';                      	
update ceproft_pa.lov_municipio t set t.codigo='421390' where t.texto='Presidente Castelo Branco';     	
update ceproft_pa.lov_municipio t set t.codigo='421460' where t.texto='Rio d Oeste';                   	
update ceproft_pa.lov_municipio t set t.codigo='421690' where t.texto='São Lourenço d Oeste';          	
update ceproft_pa.lov_municipio t set t.codigo='421720' where t.texto='São Miguel d Oeste';            	
update ceproft_pa.lov_municipio t set t.codigo='4305405' where t.texto='Chiapeta';                        
update ceproft_pa.lov_municipio t set t.codigo='430637' where t.texto='Dilermano de Aguiar';           	
update ceproft_pa.lov_municipio t set t.codigo='431555' where t.texto='Rio dos µndios';                	
update ceproft_pa.lov_municipio t set t.codigo='431710' where t.texto='Santana do Livramento';         	
update ceproft_pa.lov_municipio t set t.codigo='500200' where t.texto='Bataiporã';                      	
update ceproft_pa.lov_municipio t set t.codigo='510336' where t.texto='Conquista Do Oeste';            	
update ceproft_pa.lov_municipio t set t.codigo='510380' where t.texto='Figueirópolis d Oeste';         	
update ceproft_pa.lov_municipio t set t.codigo='510395' where t.texto='Glória d Oeste';                	
update ceproft_pa.lov_municipio t set t.codigo='510523' where t.texto='Lambari d Oeste';               	
update ceproft_pa.lov_municipio t set t.codigo='510562' where t.texto='Mirassol d Oeste';              	
update ceproft_pa.lov_municipio t set t.codigo='510791' where t.texto='Boa Esperança do Norte';        	
update ceproft_pa.lov_municipio t set t.codigo='522000' where t.texto='São João d Aliança';             	
update ceproft_pa.lov_municipio t set t.codigo='522070' where t.texto='Sítio d Abadia';                 	


