select 'insert into sptsigloacervoam.' || t.table_name || ' select * from ' || t.table_name || '@siglo_iteam;' from dba_tables t where t.table_name in ('LOV_SETOR',
'LOV_SITUACAO_IMPORTACAO','LOV_SITUACAO_USUARIO','TAB_DENOMINACAO_IMOVEL','TAB_GLEBA','TAB_LIVRO_REGISTRO','TAB_LIVRO_REGISTRO_CONFRO','TAB_LIVRO_REGISTRO_PESSOA',
'TAB_LIVRO_TOMBO','TAB_LIVRO_TOMBO_PESSOA','TAB_MODALIDADE','TAB_PESSOA','TAB_PROCESSO','TAB_PROJETO','TAB_REGISTRO_FUNDIARIO','TAB_REGISTRO_FUNDIARIO_CONFRO',
'TAB_REGISTRO_FUNDIARIO_PESSOA','TAB_SITUACAO_HIST_PROCESSO','TAB_SITUACAO_IMOVEL','TAB_SITUACAO_TITULO_FUNDIARIO','TAB_SYSCOORD','TAB_TIPO_PROCESSO','TAB_TITULO') and
t.owner='SPTSIGLOACERVOAM' ORDER BY T.TABLE_NAME



