CREATE TABLESPACE ADM_SGV_BI_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/adm_sgv_bi_data_tbsa_df01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/adm_sgv_bi_data_tbsa_df02.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/adm_sgv_bi_data_tbsa_df03.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE ADM_SGV_BI_GLOBAL_TEMP_TBSA TEMPFILE 
  '+DATA/dev/datafile/adm_sgv_bi_global_temp_tbsa_df01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/adm_sgv_bi_global_temp_tbsa_df02.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/adm_sgv_bi_global_temp_tbsa_df03.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


CREATE TABLESPACE ADM_SGV_BI_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/adm_sgv_bi_indx_tbsa_df01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE EIPE DATAFILE 
  '+DATA/dev/datafile/eipe.276.747748625' SIZE 4M AUTOEXTEND ON NEXT 4M MAXSIZE 2048M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE ESB DATAFILE 
  '+DATA/dev/datafile/esb.277.747749095' SIZE 10M AUTOEXTEND ON NEXT 4M MAXSIZE 2048M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE LDAP_TENDENCIA_DATA DATAFILE 
  '+DATA/dev/datafile/ldap_tendencia_data.dbf' SIZE 5M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE MC_ENDERECO_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/mc_endereco_data_tbsa.dbf' SIZE 100m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE MC_ENDERECO_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/mc_endereco_indx_tbsa.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE MC_TERMINAL_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/mc_terminal_data_tbsa.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE MC_TERMINAL_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/mc_terminal_indx_tbsa.dbf' SIZE 40M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M02 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m02.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M03 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m03.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M04 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m04.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M05 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m05.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M06 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m06.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M07 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m07.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M08 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m08.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M09 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M10 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M11 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A13_M12 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a13_m12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M01 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m01.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M02 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m02.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M03 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m03.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M04 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m04.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M05 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m05.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M06 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m06.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M07 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m07.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M08 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m08.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M09 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M10 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M11 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_A14_M12 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_a14_m12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_GERAL00 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_geral00.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_IDX DATAFILE 
  '+DATA/dev/datafile/part_auditoria_idx.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M02 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m02.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M03 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m03.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M04 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m04.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M05 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m05.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M06 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m06.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M07 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m07.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M08 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m08.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M09 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M10 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M11 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A13_M12 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a13_m12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M01 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m01.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M02 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m02.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M03 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m03.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M04 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m04.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M05 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m05.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M06 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m06.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M07 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m07.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M08 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m08.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M09 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M10 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M11 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_A14_M12 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_a14_m12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_GERAL00 DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_geral00.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_AUDITORIA_ITEM_IDX DATAFILE 
  '+DATA/dev/datafile/part_auditoria_item_idx.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE PART_TRN_A12_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M01.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M02.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M03.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M04.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M05.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M06.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M07.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M08.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M09.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M10.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M11.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/part_trn_A12_M11_01.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A12_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_A12_M12.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M01.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M02.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M03.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M04.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M05.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M06.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M07.dbf' SIZE 48M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M08.dbf' SIZE 100m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/part_trn_A13_M082.dbf' SIZE 100m AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M09.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M10.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M11.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A13_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_A13_M12.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M01.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M02.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M03.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M04.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M05.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M06.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M07.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M08.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M09.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M10.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M11.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_A14_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_A14_M12.dbf' SIZE 8M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_GERAL00 DATAFILE 
  '+DATA/dev/datafile/part_trn_geral00.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_IDX_AM DATAFILE 
  '+DATA/dev/datafile/part_trn_idx_am.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE PART_TRN_SUM_A12_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M01.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M02.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M03.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M04.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M05.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M06.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M07.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M08.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M09.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M10.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M11.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A12_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A12_M12.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M01.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M02.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M03.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M04.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M05.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M06.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M07.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M08.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A13_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A13_M12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M01.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M02.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M03.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M04.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M05.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M06.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M07.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M08.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_SUM_A14_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_sum_A14_M12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m01.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m02.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m03.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m04.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m05.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m06.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m07.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m08.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m09.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m10.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m11.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A12_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a12_m12.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m01.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m02.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m03.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m04.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m05.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m06.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m07.dbf' SIZE 10M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m08.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A13_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a13_m12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m01.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m02.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m03.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m04.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m05.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m06.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m07.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m08.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_A14_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_a14_m12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_GERAL00 DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_geral00.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VALORADA_IDX_AM DATAFILE 
  '+DATA/dev/datafile/part_trn_valorada_idx_am.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/part_trn_valorada_idx_am2.dbf' SIZE 10m AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A12_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a12_m05.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A12_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a12_m06.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A12_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a12_m07.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A12_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a12_m08.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A12_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a12_m09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A12_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a12_m10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A12_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a12_m11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A12_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a12_m12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m01.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m02.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m03.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m04.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m05.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m06.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m07.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m08.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A13_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a13_m12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M01 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m01.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M02 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m02.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M03 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m03.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M04 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m04.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M05 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m05.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M06 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m06.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M07 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m07.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M08 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m08.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M09 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M10 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M11 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M12 DATAFILE 
  '+DATA/dev/datafile/part_trn_val_sum_a14_m12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE PRIVATE_DATA DATAFILE 
  '+DATA/dev/datafile/private_data01.dbf' SIZE 500M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE PRIVATE_INDEX DATAFILE 
  '+DATA/dev/datafile/index/private_index01.dbf' SIZE 500M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE PRIVATE_TEMP TEMPFILE 
  '+DATA/dev/datafile/private_temp01.dbf' SIZE 100M AUTOEXTEND OFF
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


CREATE TABLESPACE PUMAFS DATAFILE 
  '+DATA/dev/datafile/pumafs.278.747749105' SIZE 4M AUTOEXTEND ON NEXT 4M MAXSIZE 2048M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SCVFS DATAFILE 
  '+DATA/dev/datafile/scvfs.279.747749115' SIZE 4M AUTOEXTEND ON NEXT 4M MAXSIZE 2048M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SENFF_DATA DATAFILE 
  '+DATA/dev/datafile/senff_data.dbf' SIZE 256M AUTOEXTEND ON NEXT 64M MAXSIZE 32767M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SENFF_INDEX DATAFILE 
  '+DATA/dev/datafile/index/senff_index.dbf' SIZE 256M AUTOEXTEND ON NEXT 64M MAXSIZE 32767M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE SENFF_TEMP TEMPFILE 
  '+DATA/dev/datafile/senff_temp.dbf' SIZE 128M AUTOEXTEND ON NEXT 1M MAXSIZE 32767M
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


CREATE TABLESPACE SGV_ACE_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_ace_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_ACE_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_ace_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_ALO_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_alo_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_ALO_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_alo_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_AUD_DATA_REVA DATAFILE 
  '+DATA/dev/datafile/sgv_aud_data_reva_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_AUD_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_aud_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_AUD_INDX_REVA DATAFILE 
  '+DATA/dev/datafile/index/sgv_aud_indx_reva_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_AUD_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_aud_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_CAD_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_cad_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_CAD_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_cad_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_CEP_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_cep_data_tbsa_df01.dbf' SIZE 300M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_CEP_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_cep_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_COB_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_cob_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_COB_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_cob_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_COBRANCA_2011 DATAFILE 
  '+DATA/dev/datafile/sgv_cobranca_2011.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_COBRANCA_2012 DATAFILE 
  '+DATA/dev/datafile/sgv_cobranca_2012.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_COBRANCA_2013 DATAFILE 
  '+DATA/dev/datafile/sgv_cobranca_2013.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_COBRANCA_2014 DATAFILE 
  '+DATA/dev/datafile/sgv_cobranca_2014.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_COBRANCA_2015 DATAFILE 
  '+DATA/dev/datafile/sgv_cobranca_2015.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_COMMON_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_common_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 504K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_COMMON_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_common_indx_tbsa_df01.dbf' SIZE 200M AUTOEXTEND ON NEXT 504K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_EQP_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_eqp_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_EQP_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_eqp_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_FTR_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_ftr_data_tbsa_df01.dbf' SIZE 276M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_FTR_DATA_TBSB DATAFILE 
  '+DATA/dev/datafile/sgv_ftr_data_tbsb.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_FTR_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_ftr_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE SGV_GLOBAL_TEMP_TBSA TEMPFILE 
  '+DATA/dev/datafile/sgv_global_temp_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 250M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


CREATE TABLESPACE SGV_INT_IDX_TMP_DF DATAFILE 
  '+DATA/dev/datafile/index/sgv_int_idx_tmp_df.dbf' SIZE 20M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_INT_TMP_DF DATAFILE 
  '+DATA/dev/datafile/sgv_int_tmp_df.dbf' SIZE 20M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_JDE_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_jde_data_tbsa.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_JDE_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_jde_indx_tbsa.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_LOB_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_lob_data_tbsa_df02.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_lob_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_LOB_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_lob_indx_tbsa_df01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_PIN_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_pin_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_PIN_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_pin_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_PRC_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_prc_data_tbsa_df01.dbf' SIZE 300M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_PRC_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_prc_indx_tbsa_df01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_SALDOS_DATA DATAFILE 
  '+DATA/dev/datafile/sgv_saldos_data.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_SALDOS_INDX DATAFILE 
  '+DATA/dev/datafile/index/sgv_saldos_indx.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_SEX_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_sex_data_tbsa_df01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_SEX_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_sex_indx_tbsa_df01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_SFA_TMP_DF DATAFILE 
  '+DATA/dev/datafile/sgv_sfa_tmp_df.dbf' SIZE 5M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TRANS_VALORADA_INDX DATAFILE 
  '+DATA/dev/datafile/index/sgv_trans_valorada_indx02.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/index/sgv_trans_valorada_indx.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TRN_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sgv_trn_data_tbsa_df02.dbf' SIZE 1384M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_trn_data_tbsa_df03.dbf' SIZE 1394M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_trn_data_tbsa_df04.dbf' SIZE 2434M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_trn_data_tbsa_df01.dbf' SIZE 1405M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TRN_DATA_TBSB DATAFILE 
  '+DATA/dev/datafile/sgv_trn_data_tbsb_df01.dbf' SIZE 794752K AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TRN_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sgv_trn_indx_tbsa_df01.dbf' SIZE 3173312K AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TRN_INDX_TBSB DATAFILE 
  '+DATA/dev/datafile/index/sgv_trn_indx_tbsb_df01.dbf' SIZE 275264K AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVD_DEST_EST_EMP_DBR DATAFILE 
  '+DATA/dev/datafile/sgv_tvd_dest_est_emp_dbr.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVD_DEST_EST_EMP_OUT DATAFILE 
  '+DATA/dev/datafile/sgv_tvd_dest_est_emp_out02.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_tvd_dest_est_emp_out.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVD_DEST_EST_EMP_TEN DATAFILE 
  '+DATA/dev/datafile/sgv_tvd_dest_est_emp_ten.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVD_DEST_OUT_EMP_DBR DATAFILE 
  '+DATA/dev/datafile/sgv_tvd_dest_out_emp_dbr.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVD_DEST_OUT_EMP_OUT DATAFILE 
  '+DATA/dev/datafile/sgv_tvd_dest_out_emp_out2.dbf' SIZE 1912512K AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_tvd_dest_out_emp_out.dbf' SIZE 2800064K AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVD_DEST_OUT_EMP_TEN DATAFILE 
  '+DATA/dev/datafile/sgv_tvd_dest_out_emp_ten.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVI_IN01 DATAFILE 
  '+DATA/dev/datafile/sgv_tvi_emp_ten_dest_est.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVI_IN02 DATAFILE 
  '+DATA/dev/datafile/sgv_tvi_emp_ten_dest_out.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVI_IN03 DATAFILE 
  '+DATA/dev/datafile/sgv_tvi_emp_dbr_dest_est.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVI_IN04 DATAFILE 
  '+DATA/dev/datafile/sgv_tvi_emp_dbr_dest_out.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SGV_TVI_IN05 DATAFILE 
  '+DATA/dev/datafile/sgv_tvi_emp_out_dest_est.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SIG_DATA_ARCHIVE DATAFILE 
  '+DATA/dev/datafile/sig_data_archive_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SIG_DATA_CONFIRMADO DATAFILE 
  '+DATA/dev/datafile/sig_data_confirmado_df01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SIG_DATA_CONTROLE DATAFILE 
  '+DATA/dev/datafile/sig_data_controle_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SIG_DATA_CURRENT DATAFILE 
  '+DATA/dev/datafile/sig_data_current_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SIG_DATA_PROCESSADO DATAFILE 
  '+DATA/dev/datafile/sig_data_processado_df01.dbf' SIZE 20M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SIG_DATA_PROCESSANDO DATAFILE 
  '+DATA/dev/datafile/sig_data_processando_df01.dbf' SIZE 20M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SIG_INDEXES DATAFILE 
  '+DATA/dev/datafile/index/sig_indexes_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SIG_INDX_CONTROLE DATAFILE 
  '+DATA/dev/datafile/index/sig_indx_controle_df01.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SIT_COMMON_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/sit_common_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SIT_COMMON_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/sit_common_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE SIT_GLOBAL_TEMP_TBSA TEMPFILE 
  '+DATA/dev/datafile/sit_global_temp_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;



CREATE TABLESPACE TEND_COMMON_DATA_TBSA DATAFILE 
  '+DATA/dev/datafile/tend_common_data_tbsa_df01.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE TEND_COMMON_INDX_TBSA DATAFILE 
  '+DATA/dev/datafile/index/tend_common_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE TEND_GLOBAL_TEMP_TBSA TEMPFILE 
  '+DATA/dev/datafile/tend_global_temp_tbsa_df01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


CREATE TABLESPACE TRANS_VAL_SUM_IDX DATAFILE 
  '+DATA/dev/datafile/index/trans_val_sum_idx.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE TRN_VALORADA_SUMARIZADA_IDX DATAFILE 
  '+DATA/dev/datafile/index/trn_valorada_sumarizada_idx.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


