 
CREATE TABLESPACE EIPE DATAFILE
  '+DATA/dev/datafile/eipe.dbf' SIZE 4M AUTOEXTEND ON NEXT 4M MAXSIZE 2048M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 

 
CREATE TABLESPACE ESB DATAFILE
  '+DATA/dev/datafile/esb.dfb' SIZE 10M AUTOEXTEND ON NEXT 4M MAXSIZE 2048M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
 
CREATE TABLESPACE MC_ENDERECO_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/mc_endereco_indx_tbsa.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE MC_TERMINAL_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/mc_terminal_indx_tbsa.dbf' SIZE 40M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M04 DATAFILE
  '+DATA/dev/datafile/part_trn_val_sum_a14_m04.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 

CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M05 DATAFILE
  '+DATA/dev/datafile/part_trn_val_sum_a14_m05.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 

CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M06 DATAFILE
  '+DATA/dev/datafile/part_trn_val_sum_a14_m06.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M07 DATAFILE
  '+DATA/dev/datafile/part_trn_val_sum_a14_m07.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M08 DATAFILE
  '+DATA/dev/datafile/part_trn_val_sum_a14_m08.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M09 DATAFILE
  '+DATA/dev/datafile/part_trn_val_sum_a14_m09.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M10 DATAFILE
  '+DATA/dev/datafile/part_trn_val_sum_a14_m10.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M11 DATAFILE
  '+DATA/dev/datafile/part_trn_val_sum_a14_m11.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE PART_TRN_VAL_SUM_A14_M12 DATAFILE
  '+DATA/dev/datafile/part_trn_val_sum_a14_m12.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE PRIVATE_DATA DATAFILE
  '+DATA/dev/datafile/private_data01.dbf' SIZE 500M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE PRIVATE_INDEX DATAFILE
  '+DATA/dev/datafile/private_index01.dbf' SIZE 500M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE PUMAFS DATAFILE
  '+DATA/dev/datafile/pumafs.dbf' SIZE 4M AUTOEXTEND ON NEXT 4M MAXSIZE 2048M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SCVFS DATAFILE
  '+DATA/dev/datafile/scvfs.dbf' SIZE 4M AUTOEXTEND ON NEXT 4M MAXSIZE 2048M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SENFF_DATA DATAFILE
  '+DATA/dev/datafile/senff_data.dbf' SIZE 256M AUTOEXTEND ON NEXT 64M MAXSIZE 32767M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SENFF_INDEX DATAFILE
  '+DATA/dev/datafile/senff_index.dbf' SIZE 256M AUTOEXTEND ON NEXT 64M MAXSIZE 32767M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_ACE_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_ace_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_ACE_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_ace_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_ALO_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_alo_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_ALO_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_alo_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_AUD_DATA_REVA DATAFILE
  '+DATA/dev/datafile/sgv_aud_data_reva_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_AUD_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_aud_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_AUD_INDX_REVA DATAFILE
  '+DATA/dev/datafile/sgv_aud_indx_reva_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_AUD_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_aud_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_CAD_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_cad_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_CAD_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_cad_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_CEP_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_cep_data_tbsa_df01.dbf' SIZE 300M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_CEP_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_cep_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_COB_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_cob_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_COB_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_cob_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_COBRANCA_2011 DATAFILE
  '+DATA/dev/datafile/sgv_cobranca_2011.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_COBRANCA_2012 DATAFILE
  '+DATA/dev/datafile/sgv_cobranca_2012.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_COBRANCA_2013 DATAFILE
  '+DATA/dev/datafile/sgv_cobranca_2013.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_COBRANCA_2014 DATAFILE
  '+DATA/dev/datafile/sgv_cobranca_2014.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_COBRANCA_2015 DATAFILE
  '+DATA/dev/datafile/sgv_cobranca_2015.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_COMMON_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_common_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 504K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_COMMON_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_common_indx_tbsa_df01.dbf' SIZE 200M AUTOEXTEND ON NEXT 504K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_EQP_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_eqp_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_EQP_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_eqp_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_FTR_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_ftr_data_tbsa_df01.dbf' SIZE 276M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_FTR_DATA_TBSB DATAFILE
  '+DATA/dev/datafile/sgv_ftr_data_tbsb.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_FTR_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_ftr_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SGV_INT_IDX_TMP_DF DATAFILE
  '+DATA/dev/datafile/sgv_int_idx_tmp_df.dbf' SIZE 20M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_INT_TMP_DF DATAFILE
  '+DATA/dev/datafile/sgv_int_tmp_df.dbf' SIZE 20M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_JDE_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_jde_data_tbsa.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_JDE_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_jde_indx_tbsa.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_LOB_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_lob_data_tbsa_df02.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_lob_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_LOB_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_lob_indx_tbsa_df01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_PIN_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_pin_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_PIN_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_pin_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_PRC_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_prc_data_tbsa_df01.dbf' SIZE 300M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_PRC_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_prc_indx_tbsa_df01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_SALDOS_DATA DATAFILE
  '+DATA/dev/datafile/sgv_saldos_data.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_SALDOS_INDX DATAFILE
  '+DATA/dev/datafile/sgv_saldos_indx.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_SEX_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_sex_data_tbsa_df01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_SEX_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_sex_indx_tbsa_df01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_SFA_TMP_DF DATAFILE
  '+DATA/dev/datafile/sgv_sfa_tmp_df.dbf' SIZE 5M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TRANS_VALORADA_INDX DATAFILE
  '+DATA/dev/datafile/sgv_trans_valorada_indx02.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_trans_valorada_indx.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TRN_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_trn_data_tbsa_df02.dbf' SIZE 1384M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_trn_data_tbsa_df03.dbf' SIZE 1394M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_trn_data_tbsa_df04.dbf' SIZE 2434M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_trn_data_tbsa_df01.dbf' SIZE 1405M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TRN_DATA_TBSB DATAFILE
  '+DATA/dev/datafile/sgv_trn_data_tbsb_df01.dbf' SIZE 794752K AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TRN_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sgv_trn_indx_tbsa_df01.dbf' SIZE 3173312K AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TRN_INDX_TBSB DATAFILE
  '+DATA/dev/datafile/sgv_trn_indx_tbsb_df01.dbf' SIZE 275264K AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVD_DEST_EST_EMP_DBR DATAFILE
  '+DATA/dev/datafile/sgv_tvd_dest_est_emp_dbr.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVD_DEST_EST_EMP_OUT DATAFILE
  '+DATA/dev/datafile/sgv_tvd_dest_est_emp_out02.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_tvd_dest_est_emp_out.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVD_DEST_EST_EMP_TEN DATAFILE
  '+DATA/dev/datafile/sgv_tvd_dest_est_emp_ten.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVD_DEST_OUT_EMP_DBR DATAFILE
  '+DATA/dev/datafile/sgv_tvd_dest_out_emp_dbr.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVD_DEST_OUT_EMP_OUT DATAFILE
  '+DATA/dev/datafile/sgv_tvd_dest_out_emp_out2.dbf' SIZE 1912512K AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED,
  '+DATA/dev/datafile/sgv_tvd_dest_out_emp_out.dbf' SIZE 2800064K AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVD_DEST_OUT_EMP_TEN DATAFILE
  '+DATA/dev/datafile/sgv_tvd_dest_out_emp_ten.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVI_IN01 DATAFILE
  '+DATA/dev/datafile/sgv_tvi_emp_ten_dest_est.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVI_IN02 DATAFILE
  '+DATA/dev/datafile/sgv_tvi_emp_ten_dest_out.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVI_IN03 DATAFILE
  '+DATA/dev/datafile/sgv_tvi_emp_dbr_dest_est.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVI_IN04 DATAFILE
  '+DATA/dev/datafile/sgv_tvi_emp_dbr_dest_out.dbf' SIZE 32M AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SGV_TVI_IN05 DATAFILE
  '+DATA/dev/datafile/sgv_tvi_emp_out_dest_est.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SIG_DATA_ARCHIVE DATAFILE
  '+DATA/dev/datafile/sig_data_archive_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SIG_DATA_CONFIRMADO DATAFILE
  '+DATA/dev/datafile/sig_data_confirmado_df01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SIG_DATA_CONTROLE DATAFILE
  '+DATA/dev/datafile/sig_data_controle_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SIG_DATA_CURRENT DATAFILE
  '+DATA/dev/datafile/sig_data_current_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SIG_DATA_PROCESSADO DATAFILE
  '+DATA/dev/datafile/sig_data_processado_df01.dbf' SIZE 20M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SIG_DATA_PROCESSANDO DATAFILE
  '+DATA/dev/datafile/sig_data_processando_df01.dbf' SIZE 20M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SIG_INDEXES DATAFILE
  '+DATA/dev/datafile/sig_indexes_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SIG_INDX_CONTROLE DATAFILE
  '+DATA/dev/datafile/sig_indx_controle_df01.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SIT_COMMON_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/sit_common_data_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE SIT_COMMON_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/sit_common_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE TEND_COMMON_DATA_TBSA DATAFILE
  '+DATA/dev/datafile/tend_common_data_tbsa_df01.dbf' SIZE 10M AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE TEND_COMMON_INDX_TBSA DATAFILE
  '+DATA/dev/datafile/tend_common_indx_tbsa_df01.dbf' SIZE 10m AUTOEXTEND ON NEXT 10m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE TRANS_VAL_SUM_IDX DATAFILE
  '+DATA/dev/datafile/trans_val_sum_idx.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
CREATE TABLESPACE TRN_VALORADA_SUMARIZADA_IDX DATAFILE
  '+DATA/dev/datafile/trn_valorada_sumarizada_idx.dbf' SIZE 10m AUTOEXTEND ON NEXT 32m MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
 
