select 'noaudit INSERT TABLE,update TABLE , delete TABLE by ' || t.user_name || ' WHENEVER NOT SUCCESSFUL ;' from sys.dba_stmt_audit_opts t

select 'audit INSERT TABLE,update TABLE , delete TABLE by ' || a.username || ' WHENEVER SUCCESSFUL ;'from dba_users a  
where a.user_id > 180
and a.username  not in('AGENOR_FILHO','ALEXANDRE_GONZE','CARLOS_ESPINOZA','CATIANE_CUSSATE','CLEBER_SAGE','CRISTIANE_VIANNA','DIEGO_FERNANDES','EMANOEL_ASSUNCAO',
'FABIO_UZEDA','FELIPE_OLIVEIRA','FERNANDO_CASTRO','GABRIEL_TOMAS','GUSTAVO_ALMEIDA','ISABELLA_GOMES','JONATHAN_ARAUJO','JORGE_FERREIRA','JULIO_DONATI',
'JUNIOR_SILVA','LEOCADIO_RODRIGUES','LUCIO_CUNHA','LUIZ_FERNANDO','LUIZ_GASPAR','MARCELO_MEDEIROS','MARCELO_SAGE','PAVALO_QUEIROZ','PAVAN','RAFAEL_COUTINHO',
'RAUL_MULET','RICARDO_BESSA','SANDRA_MULET','TUFFIC_EFRAINE','VALDIR_ARAUJO','VANESSA_NISHI','VANIA_CANCELLO','WALLACE_SILVA','WILSON_JUNIOR') 

(select distinct(b.user_name) from dba_stmt_audit_opts b)

noaudit INSERT TABLE,update TABLE , delete TABLE by WALLACE_SILVA WHENEVER NOT SUCCESSFUL ;
