
CREATE TABLESPACE PART_AUDITORIA_A16_M03 DATAFILE 
  '+DATA1/p00corp/datafile/part_auditoria_a16_m03.dbf' SIZE 1M AUTOEXTEND ON NEXT 10k MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE PART_AUDITORIA_ITEM_A16_M03 DATAFILE 
  '+DATA1/p00corp/datafile/part_auditoria_item_a16_m03.dbf' SIZE 10M AUTOEXTEND ON NEXT 10k MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;




CREATE TABLESPACE PART_TRN_A16_M03 DATAFILE 
  '+DATA1/p00corp/datafile/part_trn_a16_m03.dbf' SIZE 10m AUTOEXTEND ON NEXT 10k MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE PART_TRN_VAL_SUM_A16_M03 DATAFILE 
  '+DATA1/p00corp/datafile/part_trn_val_sum_a16_m03.dbf' SIZE 10m AUTOEXTEND ON NEXT 32K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE PART_TRN_VALORADA_A16_M03 DATAFILE 
  '+DATA1/p00corp/datafile/part_trn_valorada_a16_m03.dbf' SIZE 10m AUTOEXTEND ON NEXT 32K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
