CREATE TABLESPACE SIGLOLAB_DATA LOGGING DATAFILE 'D:\\oracle\product\10.2.0\oradata\oradev1\SIGLOLAB_DATA.dbf'
SIZE 200M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
 
CREATE TEMPORARY TABLESPACE SIGLOLAB_TEMP TEMPFILE 'D:\\oracle\product\10.2.0\oradata\oradev1\SIGLOLAB_TEMP.dbf'
SIZE 200M
AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 100M;
 
CREATE TABLESPACE SIGLOLAB_INDEX LOGGING DATAFILE 'D:\\oracle\product\10.2.0\oradata\oradev1\SIGLOLAB_INDEX.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;

CREATE USER siglolab IDENTIFIED BY siglolab
DEFAULT TABLESPACE siglolab_DATA TEMPORARY TABLESPACE siglolab_TEMP
QUOTA UNLIMITED ON siglolab_DATA
QUOTA UNLIMITED ON siglolab_INDEX;
GRANT CONNECT TO siglolab;

CREATE USER tsiglolab IDENTIFIED BY siglolab
DEFAULT TABLESPACE siglolab_DATA TEMPORARY TABLESPACE siglolab_TEMP
QUOTA UNLIMITED ON siglolab_DATA
QUOTA UNLIMITED ON siglolab_INDEX;
GRANT CONNECT TO siglolab;
